name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: execute
      run: ./hello > hello.actual
    - name: diff
      run: diff -y hello.actual hello.expect
    - name: compare
      run: cmp hello.actual hello.expect
